




USE MyTestDB2;
GO
  
/****** Object:  Index [IX_CA_CIELOCV_FK_EMPRESA]    Script Date: 11/1/2023 11:33:47 AM ******/
CREATE NONCLUSTERED INDEX [IDX_UserTab_Id] ON [dbo].[UserTab]
(
	Id ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, 
	ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO





